name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: 1.10.4
            otp: 21.3
          - elixir: 1.11
            otp: 21.3
          - elixir: 1.12
            otp: 22.3
          - elixir: 1.13
            otp: 23.3
          - elixir: 1.13
            otp: 24.3
          - elixir: 1.14
            otp: 24.3
          - elixir: 1.14
            otp: 25.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
      env:
        PROPCHECK_NUMTESTS: 999
        PROPCHECK_VERBOSE: 1

